config/routes.rb
RedmineApp::Application.routes.draw do
  get "show_orphan_revisons/:project_id/:version/:from/:to", :to => "redmine_orphan_revisions#show_orphan_revisons", :as => "orphan_revisions"
end

app/controllers/redmine_orphan_revisions_controller.rb
class RedmineOrphanRevisionsController < ApplicationController
  unloadable

  def show_orphan_revisons
    @project = Project.find(params[:project_id])
    @version = Version.find(params[:version])

    issues_in_release = Issue.where(:fixed_version_id => @version.id).pluck(:id).join(',') + "0"
    revisions = Changeset.where("committed_on > ? and committed_on < ?",params[:from],params[:to]).joins("left join changesets_issues ci on ci.changeset_id = changesets.id")

    if issues_in_release.size > 0
      @revisions_in_wrong_version = revisions.where("ci.issue_id is not null and ci.issue_id not in (#{issues_in_release})")
    end

    @orphan_revisions = revisions.where("ci.issue_id is null")

    render 'revisions'
  end
end

app/views/redmine_orphan_revisions/revisions.haml
%h2.vesrion
  = link_to_version @version, :name => version_anchor(@version)

- if @orphan_revisions.present? || @revisions_in_wrong_version.present?

  - if @orphan_revisions.present?
    %h3 Not linked revisions
    %table.list.changesets
      %thead
        %tr
          %th #
          %th= l(:label_date)
          %th= l(:field_author)
          %th= l(:field_comments)
      %tbody
        - line_num = 1
        - @orphan_revisions.each do |changeset|
          - next if changeset.comments.include?('Merge branch')
          - next if changeset.comments.include?('Merge master')
          %tr{:class => "changeset #{cycle 'odd', 'even'}"}
            = content_tag(:td, :class => 'id') do
              = link_to_revision(changeset, changeset.repository)
            %td.committed_on= format_time(changeset.committed_on)
            %td.author= h truncate(changeset.author.to_s, :length => 30)
            %td.comments= textilizable(truncate_at_line_break(changeset.comments))
          - line_num += 1

  - if @revisions_in_wrong_version.present?
    %h3 Revisions linked to issues from another version
    %table.list.changesets
      %thead
        %tr
          %th #
          %th= l(:label_date)
          %th= l(:field_author)
          %th= l(:field_comments)
      %tbody
        - line_num = 1
        - @revisions_in_wrong_version.each do |changeset|
          - next if changeset.comments.include?('Merge branch')
          - next if changeset.comments.include?('Merge master')
          %tr{:class => "changeset #{cycle 'odd', 'even'}"}
            = content_tag(:td, :class => 'id') do
              = link_to_revision(changeset, changeset.repository)
            %td.committed_on= format_time(changeset.committed_on)
            %td.author= h truncate(changeset.author.to_s, :length => 30)
            %td.comments= textilizable(truncate_at_line_break(changeset.comments))
          - line_num += 1

- else
  %center
    Nothing to link

app/views/versions/_overview.haml
- committed_on = Version.where('effective_date < ?', version.effective_date).last.effective_date rescue (Date.today - 1.year)
- orphan_revisions = Changeset.where('committed_on > ? and committed_on < ?',committed_on,version.effective_date).joins('left join changesets_issues ci on ci.changeset_id = changesets.id').where('ci.issue_id is null')
- if orphan_revisions.size > -1
  %small
    (
    = link_to "show orphaned revs", orphan_revisions_path(@project,version,committed_on,version.effective_date)
    )
- if version.completed?
  %p= format_date(version.effective_date)
- elsif version.effective_date
  %p
    %strong= due_date_distance_in_words(version.effective_date)
    (#{format_date(version.effective_date)})
%p= h version.description
- if version.custom_field_values.any?
  %ul
    - version.custom_field_values.each do |custom_value|
      - if custom_value.value.present?
        %li
          = h custom_value.custom_field.name
          \: #{h show_value(custom_value)}
- if version.issues_count > 0
  = progress_bar([version.closed_pourcent, version.completed_pourcent], :width => '40em', :legend => ('%0.0f%' % version.completed_pourcent))
  %p.progress-info
    = link_to(l(:label_x_issues, :count => version.issues_count),                                              |
      project_issues_path(version.project, :status_id => '*', :fixed_version_id => version, :set_filter => 1)) |
    -#
    \ 
    (#{link_to_if(version.closed_issues_count > 0, l(:label_x_closed_issues_abbr, :count => version.closed_issues_count), project_issues_path(version.project, :status_id => 'c', :fixed_version_id => version, :set_filter => 1))}
    —
    \#{link_to_if(version.open_issues_count > 0, l(:label_x_open_issues_abbr, :count => version.open_issues_count), project_issues_path(version.project, :status_id => 'o', :fixed_version_id => version, :set_filter => 1))})
- else
  %p.progress-info= l(:label_roadmap_no_issues)